language: python
python:
  - '3.5'
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  user: fguillot
  password:
    secure: 1N/vMg24KBhE2diWDBB9YdyaSo09QnQiKUS8/1iaXJTwkYUdZ2qjYaYNQP5K794FE+SUjg4u0ViU4p1dNkMbOFxls2hfaif7TdzeA5GuiAvUo1oPj5dbG6A5+TDEzl9tpq/CP3u9RTDWAh281MX69L9bBTKPz5Zg8oNNJVaGKkVZ9t2IxV0ksnkXrE6GQc0QwtQmQYMwtoP4RRvW7Jkk4jkn/ShDN5Q23RIBkTaqtG9PDisVvjycHDu1DcRQvM0t13580RPhLfFlvjA1ng9BkbfYl37MQzHA2Nv6Dejktk38A7CJIIUowwc59LUXI4a9JVXEb745drB1fyTDoOgQMdRdLOCd7HXvng0ggnWmDv+zWUnfGstZ0d59A/r9y4b/kDAoALpy1vo4pldeF25sJ2KfS1bFbszku/lGOpduUtq/XZiCwmZ/zEOMC7QAItZOgxFqrb5kOOjzMxaxrumuIWIwToEuSzkvn+/b8wipbQU3RZxbMEEWyUeNi8cfz1IQwbrSXmxq6lzLPuA+deQ0Ij45ajiyUf9YwkiuNwVk2MkQkei1UnQJtbTWYRuQePJmvEss7wQRG3dPcAHljJUBt2+kYNifsOZdm5zBq09aoBAH4CRdoLNUY+kG6e4SRgk0zJ+/1iVdhYx45S/acIpz+xj7QGkOx79cICeFmalK/Xw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kanboard/kanboard-cli
